version: "3.7"
services:
  envoy:
    image: "envoyproxy/envoy:v1.17.0"
    command: /usr/local/bin/envoy -c /conf/envoy.yaml -l debug --service-cluster repro
    volumes:
      - ./conf:/conf
      - ./echo:/echo
    ports:
      - "8180:8180"
      - "8181:8181"

  echo:
    build:
      context: ./echo
      dockerfile: Dockerfile
    ports:
      - "8999:8999"

  echojs:
    build:
      context: ./echojs
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
